name: Arduino CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Download TimerOne
      run: |
        mkdir -p libraries && cd libraries
        git clone https://github.com/PaulStoffregen/TimerOne.git
        cd TimerOne
        git checkout 0f2d2d9895648ecdfed3c890c03684bf0c245cf7

    - name: Download ArduinoJoystickLibrary
      run: |
        mkdir -p libraries && cd libraries
        git clone https://github.com/MHeironimus/ArduinoJoystickLibrary.git
        cd ArduinoJoystickLibrary
        git checkout 10eda40beecf1b1b632551ba6378a169832aec17
        cp -Rfp Joystick/ ../
        # TODO: set ide env in arduino-builder
        cd ../Joystick/src
        sed -i '1i#define ARDUINO 10805' Joystick.h
        sed -i '1i#define USBCON true' Joystick.h

    - name: Build Sketches
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        sketchDirectory: ./
        libraries: "libraries"
        board: "arduino:avr:uno"
